ms-auth:
    image: ${DOCKERHUB_USER}/trainself-ms-auth:latest
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_PROFILES_ACTIVE=oracle
      - ORACLE_DB_SERVICE=${ORACLE_DB_SERVICE}
      - ORACLE_DB_USER=${ORACLE_DB_USER}
      - ORACLE_DB_PASSWORD=${ORACLE_DB_PASSWORD}
    volumes:
      - ./wallet:/app/wallet:ro
    restart: always
    networks:
      - trainself-net

  ms-usuarios:
    image: ${DOCKERHUB_USER}/trainself-ms-usuarios:latest
    environment:
      - SPRING_PROFILES_ACTIVE=oracle
      - ORACLE_DB_SERVICE=${ORACLE_DB_SERVICE}
      - ORACLE_DB_USER=${ORACLE_DB_USER}
      - ORACLE_DB_PASSWORD=${ORACLE_DB_PASSWORD}
    volumes:
      - ./wallet:/app/wallet:ro
    restart: always
    depends_on:
      - ms-auth
    networks:
      - trainself-net

  ms-rutinas:
    image: ${DOCKERHUB_USER}/trainself-ms-rutinas:latest
    environment:
      - SPRING_PROFILES_ACTIVE=oracle
      - ORACLE_DB_SERVICE=${ORACLE_DB_SERVICE}
      - ORACLE_DB_USER=${ORACLE_DB_USER}
      - ORACLE_DB_PASSWORD=${ORACLE_DB_PASSWORD}
    volumes:
      - ./wallet:/app/wallet:ro
    restart: always
    depends_on:
      - ms-auth
    networks:
      - trainself-net

  ms-admin:
    image: ${DOCKERHUB_USER}/trainself-ms-admin:latest
    environment:
      - SPRING_PROFILES_ACTIVE=oracle
      - ORACLE_DB_SERVICE=${ORACLE_DB_SERVICE}
      - ORACLE_DB_USER=${ORACLE_DB_USER}
      - ORACLE_DB_PASSWORD=${ORACLE_DB_PASSWORD}
    volumes:
      - ./wallet:/app/wallet:ro
    restart: always
    depends_on:
      - ms-auth
    networks:
      - trainself-net

  ms-leaderboard:
    image: ${DOCKERHUB_USER}/trainself-ms-leaderboard:latest
    environment:
      - SPRING_PROFILES_ACTIVE=oracle
      - ORACLE_DB_SERVICE=${ORACLE_DB_SERVICE}
      - ORACLE_DB_USER=${ORACLE_DB_USER}
      - ORACLE_DB_PASSWORD=${ORACLE_DB_PASSWORD}
    volumes:
      - ./wallet:/app/wallet:ro
    restart: always
    depends_on:
      - ms-auth
    networks:
      - trainself-net