

-- 1. OBJETIVOS
CREATE TABLE OBJETIVOS (
    id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre      VARCHAR2(100)  NOT NULL,
    descripcion VARCHAR2(300)
);

-- 2. USUARIOS
CREATE TABLE USUARIOS (
    id                 NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre             VARCHAR2(100)  NOT NULL,
    correo             VARCHAR2(150)  NOT NULL UNIQUE,
    password_hash      VARCHAR2(255)  NOT NULL,
    rol                VARCHAR2(20)   DEFAULT 'usuario' CHECK (rol IN ('usuario', 'admin')),
    puntos_acumulados  NUMBER(10)     DEFAULT 0,
    fecha_registro     TIMESTAMP      DEFAULT SYSTIMESTAMP
);

-- 3. RUTINAS
CREATE TABLE RUTINAS (
    id                    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre                VARCHAR2(150)  NOT NULL,
    objetivo_id           NUMBER         NOT NULL,
    nivel                 VARCHAR2(20)   CHECK (nivel IN ('principiante', 'intermedio', 'avanzado')),
    duracion_estimada_min NUMBER(5),
    fecha_creacion        TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_rutina_objetivo FOREIGN KEY (objetivo_id) REFERENCES OBJETIVOS(id)
);

-- 4. EJERCICIOS
CREATE TABLE EJERCICIOS (
    id             NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rutina_id      NUMBER         NOT NULL,
    nombre         VARCHAR2(150)  NOT NULL,
    descripcion    VARCHAR2(400),
    duracion_seg   NUMBER(5)      NOT NULL,
    descanso_seg   NUMBER(5)      DEFAULT 15,
    orden          NUMBER(3)      NOT NULL,
    url_animacion  VARCHAR2(500),
    CONSTRAINT fk_ejercicio_rutina FOREIGN KEY (rutina_id) REFERENCES RUTINAS(id) ON DELETE CASCADE
);

-- 5. SESIONES
CREATE TABLE SESIONES (
    id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id       NUMBER         NOT NULL,
    rutina_id        NUMBER         NOT NULL,
    fecha_inicio     TIMESTAMP      DEFAULT SYSTIMESTAMP,
    completada       NUMBER(1)      DEFAULT 0 CHECK (completada IN (0, 1)),
    puntos_obtenidos NUMBER(6)      DEFAULT 0,
    CONSTRAINT fk_sesion_usuario FOREIGN KEY (usuario_id) REFERENCES USUARIOS(id),
    CONSTRAINT fk_sesion_rutina  FOREIGN KEY (rutina_id)  REFERENCES RUTINAS(id)
);

-- ============================================================
--  ÍNDICES
-- ============================================================
CREATE INDEX idx_sesiones_usuario ON SESIONES(usuario_id);
CREATE INDEX idx_sesiones_rutina  ON SESIONES(rutina_id);
CREATE INDEX idx_ejercicios_rutina ON EJERCICIOS(rutina_id);
CREATE UNIQUE INDEX idx_usuarios_correo ON USUARIOS(correo);

-- ============================================================
--  DATOS DE EJEMPLO
-- ============================================================

-- Objetivos
INSERT INTO OBJETIVOS (nombre, descripcion) VALUES ('Pérdida de peso', 'Rutinas orientadas a cardio y quema calórica');
INSERT INTO OBJETIVOS (nombre, descripcion) VALUES ('Ganancia muscular', 'Rutinas de fuerza e hipertrofia');
INSERT INTO OBJETIVOS (nombre, descripcion) VALUES ('Resistencia', 'Rutinas de cardio y resistencia aeróbica');

-- Usuarios
INSERT INTO USUARIOS (nombre, correo, password_hash, rol) VALUES ('Carlos López', 'carlos@test.com', 'hash_bcrypt_1', 'usuario');
INSERT INTO USUARIOS (nombre, correo, password_hash, rol) VALUES ('María Ruiz',   'maria@test.com',  'hash_bcrypt_2', 'usuario');
INSERT INTO USUARIOS (nombre, correo, password_hash, rol, puntos_acumulados) VALUES ('Admin', 'admin@trainself.com', 'hash_bcrypt_3', 'admin', 0);

-- Rutina ejemplo
INSERT INTO RUTINAS (nombre, objetivo_id, nivel, duracion_estimada_min) VALUES ('Full Body Cardio', 1, 'principiante', 30);

-- Ejercicios de la rutina
INSERT INTO EJERCICIOS (rutina_id, nombre, descripcion, duracion_seg, descanso_seg, orden) VALUES (1, 'Sentadillas',       'Posición erecta, bajar hasta 90°',          30, 15, 1);
INSERT INTO EJERCICIOS (rutina_id, nombre, descripcion, duracion_seg, descanso_seg, orden) VALUES (1, 'Burpees',           'Salto + plancha + salto vertical',           20, 20, 2);
INSERT INTO EJERCICIOS (rutina_id, nombre, descripcion, duracion_seg, descanso_seg, orden) VALUES (1, 'Mountain Climbers', 'Plancha con rodillas al pecho en alternancia', 30, 15, 3);
INSERT INTO EJERCICIOS (rutina_id, nombre, descripcion, duracion_seg, descanso_seg, orden) VALUES (1, 'Saltos de tijera',  'Jumping jacks, brazos y piernas abiertas',   30, 20, 4);

COMMIT;
