spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

server.port=3000

jwt.secret=${JWT_SECRET}

services.auth.url=http://ms-auth:8081
services.usuarios.url=http://ms-usuarios:8082
services.rutinas.url=http://ms-rutinas:8083
services.admin.url=http://ms-admin:8084
services.leaderboard.url=http://ms-leaderboard:8085
