spring.datasource.url=jdbc:oracle:thin:@${ORACLE_DB_SERVICE}?TNS_ADMIN=/app/wallet
spring.datasource.username=${ORACLE_DB_USER}
spring.datasource.password=${ORACLE_DB_PASSWORD}
spring.datasource.driverClassName=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=validate

spring.h2.console.enabled=false

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000